// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbP8aQVi0XCjk2mLThEUsNzHP0onOBWUY',
    appId: '1:576295579457:web:26716fabd0d72429f13bc0',
    messagingSenderId: '576295579457',
    projectId: 'fooddeliveryservice-026',
    authDomain: 'fooddeliveryservice-026.firebaseapp.com',
    storageBucket: 'fooddeliveryservice-026.appspot.com',
    measurementId: 'G-JZYX0SBGJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbzJuUYjQJ9_PyEkUIer90J-O-PTWwI3o',
    appId: '1:576295579457:android:1e5ee702a12ecfedf13bc0',
    messagingSenderId: '576295579457',
    projectId: 'fooddeliveryservice-026',
    storageBucket: 'fooddeliveryservice-026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDXR3Rwjxpq_-GCpxvzM3lW8vgIq-DyVI',
    appId: '1:576295579457:ios:fa259f85dfb7c8f2f13bc0',
    messagingSenderId: '576295579457',
    projectId: 'fooddeliveryservice-026',
    storageBucket: 'fooddeliveryservice-026.appspot.com',
    iosBundleId: 'com.example.fooddeliveryservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDXR3Rwjxpq_-GCpxvzM3lW8vgIq-DyVI',
    appId: '1:576295579457:ios:fa259f85dfb7c8f2f13bc0',
    messagingSenderId: '576295579457',
    projectId: 'fooddeliveryservice-026',
    storageBucket: 'fooddeliveryservice-026.appspot.com',
    iosBundleId: 'com.example.fooddeliveryservice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbP8aQVi0XCjk2mLThEUsNzHP0onOBWUY',
    appId: '1:576295579457:web:d0af6f315cc9af3cf13bc0',
    messagingSenderId: '576295579457',
    projectId: 'fooddeliveryservice-026',
    authDomain: 'fooddeliveryservice-026.firebaseapp.com',
    storageBucket: 'fooddeliveryservice-026.appspot.com',
    measurementId: 'G-GQC06DZXDT',
  );

}